on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                  echo "Build"
            - name: Run sample bash script
              run: |
                  bash ../../hello.sh
            - name: Test
              run: |
                  echo "Test"
            - name: Deploy
              run: |
                  echo "Deploy"

    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dummy Dependencies
              run: |
                  echo '{"dependencies": {"dummy-package": "1.0.0"}}' > package.json
                  npm install
            - name: Check
              run: |
                  echo "Check"
